module2-task1 : Functions for training
Deizmos/kekstagram pull request #1
Opened 2023-05-07 18:26 UTC by Deizmos

2023-05-09 06:26 UTC, VishniakovaAlina requested changes

2023-05-09 06:26 UTC, VishniakovaAlina commented on index.html
> +  <script src="js/functions.js"></script>
Используй относительные пути

2023-05-09 06:26 UTC, VishniakovaAlina commented on js/functions.js
> +  const splitString = string.toLowerCase().split(' ').join('');
Вместо `.split(' ').join('')` лучше использовать `replaceAll()`

2023-05-09 06:26 UTC, VishniakovaAlina commented on js/functions.js
> +  return string.toLowerCase().split(' ').join('') === splitString.split('').reverse().join('');
`splitString.split('').reverse().join('')` - слишком много действий

Разбил на массив, собрал обратно
Опять разбиваешь на массив, разворачиваешь, и собираешь обратно

Упрощай

2023-05-09 06:26 UTC, VishniakovaAlina commented on js/functions.js
> +  let string = str;
`string` бесполезная переменная

2023-05-10 09:03 UTC, Deizmos commented on index.html
> +  <script src="js/functions.js"></script>
поправил

2023-05-10 09:06 UTC, Deizmos commented on js/functions.js
> +  let string = str;
Убрал

2023-05-10 09:16 UTC, Deizmos commented on js/functions.js
> +  const splitString = string.toLowerCase().split(' ').join('');
заменил

2023-05-10 09:20 UTC, Deizmos commented on js/functions.js
> +  return string.toLowerCase().split(' ').join('') === splitString.split('').reverse().join('');
s`tring.toLowerCase().replaceAll(' ', '') === [...splitString].reverse().join('') `
вот так сделал, пойдет?

2023-05-10 17:50 UTC, merged